<a href="https://colab.research.google.com/github/Sasseronj/Estatistic/blob/main/Trabalho_Final_%C3%81lgebra_linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#<center><b>TRABALHO FINAL - ÁLGEBRA LINEAR</b></center>

# **Cabeçalho**

   

1. Disciplina 
  *  SME0142 - Álgebra Linear e Aplicações (2022) 
2. Docente
  *  Cynthia de Oliveira Lage Ferreira
3. Integrantes 
  *  Carlos Filipe de Castro Lemos, 12542630
  *  João Gabriel Sasseron Roberto Amorim, 12542564  

# **Teoria**

## **Introdução**

O primeiro método de criptografia registrado surgiu há milhares de anos, com a civilização egípcia que empregava hieróglifos para a inscrição monumental e mitificação de seus costumes. Assim, desde os tempos passadas, a criptografia já era manuseada como meio de segurança para manter informações sigilosas.



Porém, com o avanço tencnológico e a intensa utilização da computação para o armazenamento de dados, a criptografia tornou-se extremamente importante para a civilição contemorânea. Pois, ela é a encarregada de manter informações privadas, como, por exemplo, senhas, dados, informações e outros.



Nesse contexto, a álgebra linear é instrumento de suma importância para a manipulação da criptografia. Afinal, ela é capaz de ordenar e modificar esses objetos através de transformações, estruturas e afins.



Neste trabalho, iremos emprerar a criptografia de dados em formas matriciais.

## **Matrizes e criptografia**


Embora existam muitos meios de se utilizar matrizes em criptografia, a forma mais simples é por meio de matrizes inversas. Assim, para a explicação do modelo empregado, serão consideradas as matrizes $A$ e $B$, sendo $B$ a inversa de $A$. Abaixo, segue um exemplo em que a matriz $A$ irá codificar a mensagem e a matriz $B$ será usada para sua decodificação.

$$
  A = \begin{bmatrix} 1 & 3\\ 1 & 5\end{bmatrix}
  \quad e \quad
  B = \begin{bmatrix} 2.5 & -1.5\\ -0.5 & 0.5\end{bmatrix}
$$

O passo inicial para a codificação da mensagem é transformar os caracteres do alfabeto (símbolos) para algarismos, cuja correspondência será a tabela ASCII - lembrando que essa tabela deve ser do conhecimento tanto do remetente quanto do destinatário. Por exemplo:

\begin{array}{|ccc|}
  \hline
  A  & B  & C  & D  & E  & F  & G  & H  & I  & J  \\
  65  & 66  & 67  & 68  & 69  & 70  & 71  & 72  & 73  & 74 \\
  \hline
  K  & L  & M  & N  & O  & P  & Q  & R  & S  & T  \\
  75  & 76  & 77  & 78  & 79  & 80  & 81  & 82  & 83  & 84 \\
  \hline
  U  & V  & W  & X  & Y  & Z  & .  & !  & \# &    \\
  85  & 86  & 87  & 88  & 89  & 90  & 35  & 33  & 83  & 240 \\
  \hline
\end{array}

Agora, somos capazes de codificar uma mensagem, utilizando técnicas de pré-processamento, e, por isso, transformaremos a mensagem "ALGEBRA LINEAR" na seguinte expressão e codificação:
  .

\begin{array}{ccc}
  \textbf{ALGEBRA#LINEAR}
\end{array}


\begin{array}{ccc}
   65& 76& 71& 69& 66& 82& 65& 35& 76 & 73 & 78 & 69 & 65 & 82
\end{array}

O símbolo $\#$ serve para não haver erros de leitura na língua portugesa após a decodificação da mensagem.

Na sequência, iremos transladar a lista de números em uma matriz de duas linhas, observando que, se o número de elemestos for ímpar, deve-se acrescentar uma caractere vazio.

$$
  M = \begin{bmatrix} 65 & 76 & 71 & 69 & 66 & 82 & 65 \\ 35 & 76 & 73 & 78 & 69 & 65 & 82\end{bmatrix}
$$

Deste modo, para a codificar a mensagem, multiplicamos a matriz $A$ por $M$, tal que $N = A \cdot M$.

$$
N = \begin{bmatrix} 1 & 3\\ 1 & 5\end{bmatrix} \cdot \begin{bmatrix} 65 & 76 & 71 & 69 & 66 & 82 & 65 \\ 35 & 76 & 73 & 78 & 69 & 65 & 82\end{bmatrix}\\
$$

$$
N = \begin{bmatrix} 170 & 304 & 290 & 303 & 273 & 277 & 311 \\ 240 & 456 & 436 & 459 & 411 & 407 & 475\end{bmatrix}
$$

Assim, a matriz $N$ representa a mensagem codificada: 


$$
\begin{array} 1170 & 304 & 290 & 303 & 273 & 277 & 311 & 240 & 456 & 436 & 459 & 411 & 407 & 475\end{array}
$$

Com a mensagems em mãos, o destinatário será capaz de decodificar a mensagem,  atráves da matriz inversa $B$.




Sabendo que $B \cdot N = B \cdot A \cdot M= I \cdot M = M$, temos que $M = B \cdot N$. 



Dessa forma, multiplicamos a matriz $B$ por $N$ e obetmos o seguinte resultado:

$$
M = \begin{bmatrix} 2.5 & -1.5\\ -0.5 & 0.5\end{bmatrix} ⋅ \begin{bmatrix} 170 & 304 & 290 & 303 & 273 & 277 & 311 \\ 240 & 456 & 436 & 459 & 411 & 407 & 475\end{bmatrix}
$$

$$
M = \begin{bmatrix} 65 & 76 & 71 & 69 & 66 & 82 & 65 \\ 35 & 76 & 73 & 78 & 69 & 65 & 82\end{bmatrix}
$$

Pro fim, encontramos a matriz original $M$. Em seguida, utilizamos a tabaleas ASCII, novamente, para transformar os algarismo em caracteres. Assim, com a transformação, temos:

\begin{array}{ccc}
   65& 76& 71& 69& 66& 82& 65& 35& 76 & 73 & 78 & 69 & 65 & 82
\end{array}


\begin{array}{ccc}
  \textbf{ALGEBRA#LINEAR}
\end{array}

# **Aplicação**

A teoria descrita acima será aplicada no código abaixo, seguindo as expecificações dadas.

In [ ]:
import numpy as np

## ***Bloco Comum***

In [ ]:
def menu() -> int:
    print("")
    print("")
    print("####### MENU PROGRAMA DE CRIPTOGRAFIA #######")
    print("#                                           #")
    print("# 1) Encriptar Mensagem                     #")
    print("# 2) Desencriptar Mensagem                  #")
    print("# 3) Sobre o programa                       #")
    print("# 4) Sair                                   #")
    print("#                                           #")
    print("#############################################")

In [ ]:
def sobre():
    print("")
    print("")
    print("#######    PROGRAMA DE CRIPTOGRAFIA   #######")
    print("#                                           #")
    print("#   Programa criado por                     #")
    print("#   - Carlos Filipe de C. Lemos (12542630)  #")
    print("#   - João Gabriel S. R. Amorim  (12542564) #")
    print("#                                           #")
    print("#############################################")
    print("")

In [ ]:
def coletar_numeros_criptograficos() -> np.array:
    m = []
    print("Digite 4 números que serão usados na manipulação da mensagem:")
    contador = 0
    while contador != 4:
        leitura = input("Numero " + str(contador+1) + ": ")        
        if leitura == '':
          pass
        elif leitura.isdigit():
            m.append(int(leitura))
            contador += 1

    return np.array(m).reshape(2, 2)

## ***Bloco de Manipulação da Mensagem***

In [ ]:
def traduz_char_int(mensagem) -> list:
  lista = []

  # A partir da mensagem em caracteres, transforma
  # em algarismos da tabela ASCII.
  for letra in mensagem:
      lista.append(ord(letra))

  return lista

In [ ]:
def preparando_mensagem(mensagem) -> str:
  mensagem = mensagem.replace(' ', '#')

  # Caso a mensagem tenha tamanho ímpar, adiciona
  # o caractere espaço ao seu fim.
  if len(mensagem) % 2 != 0:
    mensagem += "#"
  return mensagem

In [ ]:
def despreparar_mensagem(desencriptado) -> str:
    mensagem = ''

    # Percorre toda a mensagem, transformando os 
    # algarismos em caracteres, segundo a tabela
    # ASCII.
    for x in desencriptado:
        for y in x:

            # Aproxima o seu ponto flutuante para o 
            # inteiro  mais próximo. Assim, evitando
            # o problema do python de sempre arredondar
            # para baixo.
            caracter = chr(int(round(float(y), 0)))
            if caracter == '#':
              mensagem = mensagem + ' '
            else:
              mensagem = mensagem + caracter
    return mensagem

In [ ]:
def lendo_mensagem_codificada() -> np.array:

    # Mensagens nencessárias para coordenar o usuário para inserir os dados.
    print("Digite a mensagem codificada em numeros (quando terminar, digite 's' para sair): ")
    print("")
    alfanumerico = str()
    mensagem = np.array([]) 
    numero = 0
    while alfanumerico != 's':
        alfanumerico = input("Digite o número " + str(numero +1)+ ": ")
        if alfanumerico == '':
            pass
        elif alfanumerico.isdigit():
            mensagem = np.append(mensagem,[int(alfanumerico)])
            numero += 1
        elif alfanumerico == 'encriptado':
            mensagem = alfanumerico
            break
    return mensagem


In [ ]:
def lendo_mensagem():
    return input("\nDigite a mensagem que deseja criptografar: ")

## ***Bloco de Encriptação***



In [ ]:
def verificar_independencia_linear(m: np.array) -> bool:
    
    # Função responsável por verificar se a matriz $A$ fornecida é invertível. 
    # Para isso, checa se o Det(A) é igual a 0, caso seja, retorna falso, 
    # caso contrário, a matriz atende as especificações e retorna verdadeiro.
    if np.linalg.det(m) == 0:
        return False
    return True

In [ ]:
def encriptar_mensagem():
    # Sequencia: a) Lê a mensagem; b) Prepara a mensagem; c) Transforma em lista ASCII.
    mensagem = lendo_mensagem()
    lista = traduz_char_int(preparando_mensagem(mensagem))    
    print("Mensagem: ", mensagem)
    print("Mensagem em ASCII: ", lista)

    # Transformar a mensagem em uma matriz de 2 linhas e n colunas
    matriz_mensagem = np.array(lista).reshape(2, int(len(lista)/2))
    print("Matriz mensagem: \n", matriz_mensagem)

    # Cria matriz encriptadora a partir de dados informados pelo usuário
    matriz_encriptadora = np.array
    matriz_encriptadora = coletar_numeros_criptograficos()
    while verificar_independencia_linear(matriz_encriptadora) is not True:
        print("Os números usados não são inversíveis!")
        matriz_encriptadora = np.array(coletar_numeros_criptograficos()).reshape(2, 2)
    print("Matriz Encriptadora: \n", matriz_encriptadora)

    # Encriptando: N = A * M 
    encriptado = matriz_encriptadora @ matriz_mensagem 
    print("Mensagem encriptada: \n", encriptado)

    return matriz_encriptadora, encriptado, mensagem
    

## ***Bloco de Desencriptação***

In [ ]:
def cria_matriz_inversa(matriz_encriptadora: np.array) -> np.array:
    
    # Cria a matriz inversa para possibiltiar a desincriptação
    # da mensagem forncida pelo usuário.
    matriz_desencriptadora = np.zeros((2, 2), dtype=int)
    matriz_desencriptadora = np.linalg.inv(matriz_encriptadora)
    return matriz_desencriptadora

In [ ]:
def desencriptar_mensagem(matriz_encriptadora: np.array, encriptado: np.array, mensagem: str):
    # Leitura da mensagem a ser desincriptada
    mensagem_usuario = lendo_mensagem_codificada()

    # Aplicação dos processos necessários.
    if type(mensagem_usuario) == str and mensagem_usuario == 'encriptado':
        mensagem_usuario = encriptado
        matriz = matriz_encriptadora 
    else:
        mensagem_usuario = mensagem_usuario.reshape(2, int(len(mensagem_usuario)/2))
        matriz = coletar_numeros_criptograficos()

    print("Matriz da Mensagem Encriptada: \n", mensagem_usuario)

    # Matriz invesa
    matriz_desencriptadora = cria_matriz_inversa(matriz) 
    print("Matriz Desencriptadora: \n", matriz_desencriptadora)

    # Desencriptando: M = B * N 
    desencriptado = matriz_desencriptadora @ mensagem_usuario 
    print("Desencriptado: \n", desencriptado)

    desencriptado = desencriptado.tolist()
    mensagem_usuario = despreparar_mensagem(desencriptado)
    print("Mensagem Desencriptada: ")
    print(mensagem_usuario)


## ***Bloco de Execução do Programa***

In [ ]:
matriz_encriptadora = np.array
encriptado = np.array
mensagem = str()
opcao = 0

while(opcao != 4):
    menu()
    opcao = int(input("Digite a opção desejada:"))

    # Menu de opções do programa
    if opcao == 1:
        matriz_encriptadora, encriptado, mensagem = encriptar_mensagem()
    elif opcao == 2:
        desencriptar_mensagem(matriz_encriptadora, encriptado, mensagem)
    elif opcao == 3:
        sobre()



####### MENU PROGRAMA DE CRIPTOGRAFIA #######
#                                           #
# 1) Encriptar Mensagem                     #
# 2) Desencriptar Mensagem                  #
# 3) Sobre o programa                       #
# 4) Sair                                   #
#                                           #
#############################################
Digite a opção desejada:1

Digite a mensagem que deseja criptografar: Testando o programa
Mensagem:  Testando o programa
Mensagem em ASCII:  [84, 101, 115, 116, 97, 110, 100, 111, 35, 111, 35, 112, 114, 111, 103, 114, 97, 109, 97, 35]
Matriz mensagem: 
 [[ 84 101 115 116  97 110 100 111  35 111]
 [ 35 112 114 111 103 114  97 109  97  35]]
Digite 4 números que serão usados na manipulação da mensagem:
Numero 1: 1
Numero 2: 2
Numero 3: 3
Numero 4: 4
Matriz Encriptadora: 
 [[1 2]
 [3 4]]
Mensagem encriptada: 
 [[154 325 343 338 303 338 294 329 229 181]
 [392 751 801 792 703 786 688 769 493 473]]


####### MENU PROGRAMA DE CRIP